language: python

python:
  - "3.7"

before_install:
  - source .travis/setup_lua.sh

install:
  - pip install pypeg2
  - pip install coverage
  - pip install python-coveralls

script:
  - python -m site
  - python -m coverage run tests.py --x64 --linux --luabase $LUA_HOME_DIR

after_success:
  - coveralls
