language: python

python:
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - source .travis/setup_lua.sh

install:
  - pip install pypeg2
  - pip install coverage
  - pip install python-coveralls

script:
  - python3 -m coverage run tests.py --x64 --linux

after_success:
  - coveralls
