language: python

python:
  - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake3

install:
  - pip install pypeg2
  - pip install coverage
  - pip install python-coveralls

script:
  - cmake --version
  - python3 -m coverage run tests.py --x64 --linux

after_success:
  - coveralls
