from pypeg2 import re, flag, name, Plain, optional, attr, K, parse


#
typename = re.compile(r"((::)*(_|[A-z])[A-z0-9_]*)+")
ref_re = re.compile(r"[&*]+")


def get_fully_qualified_ctype_name(type):
	out = ''
	if type.const:
		out += 'const '
	out += type.unqualified_name
	if hasattr(type, 'ref'):
		out += ' ' + type.ref
	return out


def get_type_clean_name(type):
	""" Return a type name cleaned so that it may be used as variable name in the generator output."""
	parts = type.split(' ')

	def clean_type_name_part(part):
		part = part.replace('*', 'ptr')  # pointer
		part = part.replace('&', '_r')  # reference
		part = part.replace('::', '__')  # namespace
		return part

	parts = [clean_type_name_part(part) for part in parts]
	return '_'.join(parts)


def ctypes_to_string(ctypes):
	return ','.join([repr(ctype) for ctype in ctypes])


class _CType:
	def __repr__(self):
		return get_fully_qualified_ctype_name(self)

	def get_ref(self):
		return self.ref if hasattr(self, 'ref') else ''


_CType.grammar = flag("const", K("const")), optional([flag("signed", K("signed")), flag("unsigned", K("unsigned"))]), attr("unqualified_name", typename), optional(attr("ref", ref_re))


#
def clean_c_symbol_name(name):
	name = name.replace('::', '__')
	return name


#
def _prepare_ctypes(ctypes, template):
	if not type(ctypes) is type([]):
		ctypes = [ctypes]
	return [parse(type, template) for type in ctypes]


#
class _CArg:
	def __repr__(self):
		out = repr(self.ctype)
		if hasattr(self, 'name'):
			out += ' ' + str(self.name)
		return out


_CArg.grammar = attr("ctype", _CType), optional(name())


#
def ctype_ref_to(src_ref, dst_ref):
	i = 0
	while i < len(src_ref) and i < len(dst_ref):
		if src_ref[i] != dst_ref[i]:
			break
		i += 1

	src_ref = src_ref[i:]
	dst_ref = dst_ref[i:]

	if src_ref == '&':
		if dst_ref == '&':
			return ''  # ref to ref
		elif dst_ref == '*':
			return '&'  # ref to ptr
		else:
			return ''  # ref to value
	elif src_ref == '*':
		if dst_ref == '&':
			return '*'  # ptr to ref
		elif dst_ref == '*':
			return ''  # ptr to ptr
		else:
			return '*'  # ptr to value
	else:
		if dst_ref == '&':
			return ''  # value to ref
		elif dst_ref == '*':
			return '&'  # value to ptr
		else:
			return ''  # value to value


class TypeConverter:
	def __init__(self, type, storage_type=None):
		if not storage_type:
			storage_type = type

		self.ctype = parse(type, _CType)
		self.storage_ctype = parse(storage_type, _CType)

		self.clean_name = get_type_clean_name(type)
		self.fully_qualified_name = get_fully_qualified_ctype_name(self.ctype)
		self.type_tag = '__%s_type_tag' % self.clean_name

	def output_type_api(self):
		pass

	def get_ownership_policy(self, ref):
		"""Return the VM default ownership policy for a reference coming from C."""
		if ref == '*' or ref == '&':
			return 'NonOwning'
		return 'ByValue'


#
class FABGen:
	def __init__(self):
		self._setup_func_name = None
		self._namespace = None
		self._header, self._source = None, None

		self.__system_includes, self.__user_includes = None, None

		self.__type_convs = None
		self.__function_templates = None

		self._bound_functions = None

	def output_header(self):
		common = "// This file is automatically generated, do not modify manually!\n\n"

		self._source += "// FABgen .cpp\n"
		self._source += common
		self._header += "// FABgen .h\n"
		self._header += common

	def output_includes(self):
		self.add_include('cstdint', True)

		self._source += '{{{__WRAPPER_INCLUDES__}}}\n'

	def start(self, name, namespace = None):
		self._name = name
		self._namespace = namespace
		self._header, self._source = "", ""

		self.__system_includes, self.__user_includes = [], []

		self.__type_convs = {}
		self.__function_templates = {}

		self._bound_functions = []  # a list of bound functions

		self.output_header()
		self.output_includes()

		if self._namespace:
			self._header += 'namespace %s {\n\n' % self._namespace
			self._source += 'namespace %s {\n\n' % self._namespace

	def add_include(self, path, is_system_include = False):
		if is_system_include:
			self.__system_includes.append(path)
		else:
			self.__user_includes.append(path)

	def insert_code(self, code, in_source=True, in_header=True):
		if in_header:
			self._header += code
		if in_source:
			self._source += code

	#
	def raise_exception(self, type, reason):
		assert 'raise_exception not implemented in generator'

	#
	def proto_check(self, name, ctype):
		assert 'proto_check not implemented in generator'
	def proto_to_c(self, name, ctype):
		assert 'proto_check not implemented in generator'
	def proto_from_c(self, name, ctype):
		assert 'proto_check not implemented in generator'

	#
	def bind_type(self, conv):
		"""Declare a converter for a type natively supported by the target VM."""
		type = conv.fully_qualified_name
		self.__type_convs[type] = conv

		self._header += conv.output_type_api()
		self._source += 'static const char *%s = "%s";\n\n' % (conv.type_tag, type)
		self._source += conv.output_type_glue()

		self.insert_code('\n')

	#
	def get_class_default_converter(self):
		assert "missing class type default converter"

	def bind_class(self, name):
		class_default_conv = self.get_class_default_converter()
		self.bind_type(class_default_conv(name))

	#
	def select_ctype_conv(self, ctype):
		"""Select a type converter."""
		full_qualified_ctype_name = get_fully_qualified_ctype_name(ctype)

		if full_qualified_ctype_name == 'void':
			return None

		if full_qualified_ctype_name in self.__type_convs:
			return self.__type_convs[full_qualified_ctype_name]

		return self.__type_convs[ctype.unqualified_name]

	#
	def select_args_convs(self, args):
		return [{'conv': self.select_ctype_conv(arg.ctype), 'ctype': arg.ctype} for i, arg in enumerate(args)]

	def begin_convert_args(self, args):
		pass

	def decl_arg(self, ctype, name):
		return '%s %s;\n' % (get_fully_qualified_ctype_name(ctype), name)

	def cleanup_args(self, args):
		pass

	#
	def begin_convert_rvals(self, rval):
		pass

	def decl_rval(self, type, name):
		return '%s %s = ' % (get_fully_qualified_ctype_name(type), name)

	def commit_rvals(self, rval):
		assert "missing return values template"

	def cleanup_rvals(self, rval):
		pass

	#
	@staticmethod
	def __get_bind_function_name(name):
		return '_' + clean_c_symbol_name(name)

	def bind_function(self, name, rval, args):
		rval = parse(rval, _CType)
		args = _prepare_ctypes(args, _CArg)

		self.insert_code('// %s %s(%s)\n' % (rval, name, ctypes_to_string(args)), True, False)

		bound_name = self.__get_bind_function_name(name)
		self._source += self.new_function(bound_name, args)

		self._bound_functions.append({'name': name, 'bound_name': bound_name, 'rval': rval, 'args': args})

		# declare call arguments and convert them from the VM
		args = self.select_args_convs(args)
		self.begin_convert_args(args)

		c_call_args = []
		for i, arg in enumerate(args):
			conv = arg['conv']
			if not conv:
				continue

			arg_name = 'arg%d' % i
			self._source += self.decl_arg(conv.storage_ctype, arg_name)
			self._source += conv.to_c_call(self.get_arg(i, args), '&' + arg_name)

			c_call_arg_transform = ctype_ref_to(conv.storage_ctype.get_ref(), arg['ctype'].get_ref())
			c_call_args.append(c_call_arg_transform + arg_name)

		# declare return values
		rval_conv = self.select_ctype_conv(rval)
		if rval_conv:
			self._source += self.decl_rval(rval, 'rval')

		# perform function call
		self._source += '%s(%s);\n' % (name, ', '.join(c_call_args))  # perform C function call

		# cleanup arguments
		self.cleanup_args(args)

		# convert return values
		self.begin_convert_rvals(rval)
		if rval_conv:
			self.rval_from_c_ptr(rval, 'rval', rval_conv, ctype_ref_to(rval.get_ref(), rval_conv.ctype.get_ref() + '*') + 'rval')

		# commit return values
		self.commit_rvals(rval)

		# cleanup return value
		self.cleanup_rvals(rval)

		self._source += "}\n\n"

	def decl_function_template(self, tmpl_name, tmpl_args, rval, args):
		self.__function_templates[tmpl_name] = {'tmpl_args': tmpl_args, 'rval': rval, 'args': args}

	def bind_function_template(self, tmpl_name, bound_name, bind_args):
		tmpl = self.__function_templates[tmpl_name]
		tmpl_args = tmpl['tmpl_args']

		assert len(tmpl_args) == len(bind_args)

		def bind_tmpl_arg(arg):
			return bind_args[tmpl_args.index(arg)] if arg in tmpl_args else arg

		bound_rval = bind_tmpl_arg(tmpl['rval'])
		bound_args = [bind_tmpl_arg(arg) for arg in tmpl['args']]

		bound_named_args = ['%s arg%d' % (arg, idx) for idx, arg in enumerate(bound_args)]

		# output wrapper
		self._source += '// %s<%s> wrapper\n' % (tmpl_name, ', '.join(bind_args))
		self._source += 'static %s %s(%s) {\n' % (bound_rval, bound_name, ', '.join(bound_named_args))
		if bound_rval != 'void':
			self._source += 'return '
		self._source += '%s<%s>(%s);\n' % (tmpl_name, ', '.join(bind_args), ', '.join(['arg%d' % i for i in range(len(bound_args))]))
		self._source += '}\n\n'

		# bind wrapper
		self.bind_function(bound_name, bound_rval, bound_args)

	#
	def output_summary(self):
		self._source += '// Bound %d global functions:\n' % len(self._bound_functions)
		for f in self._bound_functions:
			self._source += '//	- %s bound as %s\n' % (f['name'], f['bound_name'])
		self._source += '\n'

	def finalize(self):
		# insert includes
		if len(self.__system_includes) > 0:
			system_includes = ''.join(['#include <%s>\n' % path for path in self.__system_includes])
		if len(self.__user_includes) > 0:
			user_includes = ''.join(['#include "%s"\n' % path for path in self.__user_includes])

		self._source = self._source.replace('{{{__WRAPPER_INCLUDES__}}}', system_includes + user_includes)

		# close namespace
		if self._namespace:
			self._header += '} // %s\n\n' % self._namespace
			self._source += '} // %s\n\n' % self._namespace

	def get_output(self):
		return self._header, self._source
